export const site = {
  name: 'Electricista Rápido', domain: 'https://electricistarapido.com',
  phone: '641 58 93 94', tel: '+34641589394', whatsapp: '34641589394',
  // The first release is a review build. Do not invent the missing business data.
  launchApproved: false,
  legal: { holder: '', taxId: '', address: '', email: '', reviewed: false },
  technicalReview: { name: '', date: '' },
  // Add only municipalities with confirmed coverage and genuinely local editorial content.
  localPages: {},
};
export const provinces = [
  ['48','Bizkaia','bizkaia'],['20','Gipuzkoa','gipuzkoa'],['01','Álava','alava'],
  ['39','Cantabria','cantabria'],['09','Burgos','burgos'],['31','Navarra','navarra'],
  ['26','La Rioja','la-rioja'],['33','Asturias','asturias'],['34','Palencia','palencia'],
  ['05','Ávila','avila'],['24','León','leon'],['49','Zamora','zamora'],
  ['47','Valladolid','valladolid'],['40','Segovia','segovia'],['28','Madrid','madrid'],
  ['42','Soria','soria'],['37','Salamanca','salamanca'],
].map(([id,name,slug])=>({id,name,slug}));
export const geography = {
  url: 'https://raw.githubusercontent.com/codeforspain/ds-organizacion-administrativa/1e9c99280ef4d7a12def33cafc3df59d9fc1f688/data/municipios.json',
  gitBlob: 'e757c424faea328387cc12e5893ff36c87221fe2',
  source: 'Code for Spain · ds-organizacion-administrativa (versión fijada)',
};
export const photos = {
  hero: {id:'35154098',caption:'Diagnóstico profesional de un cuadro eléctrico',alt:'Electricista con equipo de protección comprobando interruptores de un cuadro con un medidor',author:'Prashik Narnaware'},
  diferencial: {id:'34054464',caption:'Diagnóstico con multímetro',alt:'Electricista diagnosticando un cuadro eléctrico con un multímetro',author:'Bulat843'},
  corte: {id:'17842832',caption:'Revisión de cuadro y suministro',alt:'Profesional revisando un cuadro eléctrico',author:'Fatih Yurtman'},
  humedad: {id:'5691642',caption:'Cableado de una toma durante una reparación',alt:'Cableado eléctrico visible durante una reparación doméstica',author:'Ksenia Chernaya'},
  cuadro: {id:'257736',caption:'Trabajo sobre un cuadro eléctrico',alt:'Manos de un electricista trabajando en un cuadro con protecciones y cableado',author:'Pixabay'},
  mecanismos: {id:'5691590',caption:'Reparación de enchufes y mecanismos',alt:'Electricista reparando enchufes con alicates',author:'Ksenia Chernaya'},
  sobrecarga: {id:'14319099',caption:'Comprobación de circuitos',alt:'Electricista comprobando un cuadro con un multímetro',author:'Onics Energy'},
  intermitente: {id:'11679114',caption:'Equipo de medida eléctrica',alt:'Multímetro utilizado para localizar averías eléctricas',author:'Willquezada'},
  circuitos: {id:'442160',caption:'Revisión de tomas y circuitos',alt:'Profesional revisando tomas eléctricas de una vivienda',author:'Field Engineer'},
  revision: {id:'7359566',caption:'Inspección de cuadro eléctrico',alt:'Electricista inspeccionando un cuadro eléctrico',author:'Sami Abdullah'},
  urgencia: {id:'7647233',caption:'Reparación eléctrica en vivienda',alt:'Profesional trabajando sobre un mecanismo eléctrico en una vivienda',author:'Anastasia Shuraeva'},
};
export const sources = {
  rcd: ['Guía de Schneider Electric: funcionamiento del diferencial','https://www.electrical-installation.org/enwiki/Description_of_RCDs'],
  insulation: ['Guía de Schneider Electric: defectos de aislamiento y humedad','https://www.electrical-installation.org/enwiki/Protection_against_fire_due_to_insulation_failure'],
  supply: ['e-distribución: cortes y averías de suministro','https://www.edistribucion.com/es/averias.html'],
  safety: ['Guía de Schneider Electric: protección frente al choque eléctrico','https://www.electrical-installation.org/enwiki/Protection_against_electric_shock'],
  rebt: ['BOE: Reglamento electrotécnico para baja tensión','https://www.boe.es/buscar/act.php?id=BOE-A-2002-18099'],
};
export const services = [
  {slug:'diferencial-que-no-sube',name:'Diferencial que no sube',tag:'PROTECCIONES',icon:'shield',photo:'diferencial',
   title:'El diferencial no sube o salta: diagnóstico de la avería',
   intro:'Vuelve a bajarse, no se mantiene arriba o corta la luz sin un motivo aparente. Antes de sustituirlo, hay que saber qué está provocando el disparo.',
   short:'Localización de fugas y revisión de la protección que desconecta la vivienda.',
   sections:[
    ['No siempre está estropeado el diferencial','El diferencial desconecta la instalación cuando detecta una diferencia de corriente que puede corresponder a una fuga. Que salte no demuestra que esté averiado: puede estar respondiendo a un defecto de la instalación o de un aparato.'],
    ['Qué información ayuda a localizar el fallo','Indica si el salto es inmediato o aparece después de un rato, si coincide con un aparato y si ha ocurrido después de lluvia, una obra o una filtración. Son pistas para organizar la revisión, no un diagnóstico por teléfono.'],
    ['Revisión del circuito y del dispositivo','El profesional comprueba el aislamiento, los receptores asociados y el comportamiento de la protección, según lo que encuentre. La propuesta de reparación debe responder a esas comprobaciones.'],
    ['Lo que no debes hacer','No fuerces la palanca ni anules la protección para mantener la luz. No retires tapas ni manipules el interior del cuadro. Si existe humedad, olor a quemado o chispas, mantente alejado y solicita ayuda.']],
   faq:[['¿Cambiar el diferencial soluciona cualquier salto?','No. Si existe una fuga persistente, hay que reparar su origen. Solo se propone sustituir la protección cuando la comprobación lo justifica.'],['¿Un diferencial superinmunizado arregla un cable mojado?','No repara un defecto de aislamiento. La elección de la protección corresponde al profesional y no sustituye la reparación de la instalación.']], sources:['rcd','safety'], related:['humedad-y-derivaciones','averias-intermitentes','reparacion-cuadros-electricos']},
  {slug:'sin-luz-en-casa',name:'Sin luz en casa',tag:'CORTES DE LUZ',icon:'bolt',photo:'corte',
   title:'Sin luz en casa: avería particular o corte de suministro',
   intro:'Un apagón puede afectar solo a la vivienda, a una parte del edificio o a la red. Identificar el alcance permite orientar el aviso al servicio adecuado.',
   short:'Diagnóstico de apagones particulares y circuitos que se quedan sin suministro.',
   sections:[
    ['¿Solo tu vivienda o también los vecinos?','Comunica si otros vecinos o zonas comunes tienen electricidad, siempre sin acercarte a instalaciones dañadas. Esa información orienta la revisión, aunque por sí sola no confirma dónde está la avería.'],
    ['Automáticos arriba y vivienda sin electricidad','La posición de las palancas no garantiza que llegue alimentación. Puede intervenir el control de potencia del contador u otro fallo anterior a los circuitos interiores. No abras el contador ni manipules elementos precintados.'],
    ['Cuando la incidencia pertenece a la red','Los cortes generales corresponden a la distribuidora que figura en tu factura. Este servicio no es el teléfono de averías de una compañía eléctrica ni puede garantizar la reposición de su red.'],
    ['Qué contar al solicitar la revisión','Indica desde cuándo estás sin luz, si es un corte total o parcial y si había varios aparatos funcionando. Si dependes de un equipo médico y existe un riesgo inmediato para una persona, contacta con emergencias.']],
   faq:[['¿Podéis arreglar un apagón de todo el pueblo?','No intervenimos en la red de distribución. La incidencia debe comunicarse a la distribuidora correspondiente.'],['¿Hace falta tocar el cuadro para pedir ayuda?','No. Describe lo que observas sin retirar tapas ni manipular cableado. Las comprobaciones técnicas corresponden al profesional.']],sources:['supply'],related:['sobrecargas-y-cortocircuitos','diferencial-que-no-sube','circuitos-enchufes-alumbrado']},
  {slug:'humedad-y-derivaciones',name:'Humedad y derivaciones',tag:'AISLAMIENTO',icon:'drop',photo:'humedad',
   title:'Averías eléctricas por humedad y derivaciones',
   intro:'Si los cortes coinciden con lluvia, condensación o una filtración, conviene revisar el aislamiento y el punto por el que llega la humedad.',
   short:'Revisión de cables, cajas y conexiones afectados por agua o condensación.',
   sections:[
    ['El cable mojado no es la única posibilidad','La entrada de agua puede afectar a cajas, mecanismos, luminarias o conexiones. La coincidencia con la lluvia es una pista; no permite asegurar qué componente falla sin revisar la instalación.'],
    ['La avería puede desaparecer y volver','Que el circuito vuelva a funcionar cuando se seca no demuestra que el aislamiento esté en buen estado. La humedad y la contaminación pueden favorecer corrientes de fuga y deterioro de los materiales.'],
    ['Reparar la parte eléctrica y resolver la entrada de agua','Según el diagnóstico, puede ser necesario sustituir componentes deteriorados y coordinar la corrección de una filtración. Secar o tapar superficialmente un elemento no acredita una reparación segura.'],
    ['No te acerques a un elemento eléctrico mojado','No toques cables, cuadros, enchufes ni aparatos afectados por agua. No intentes secarlos con calor ni manipularlos para tomar una fotografía. Ante peligro inmediato, aléjate y llama al 112.']],
   faq:[['¿Puede saltar solo cuando llueve?','Sí, la humedad puede estar relacionada con un defecto de aislamiento. La revisión debe confirmar el origen concreto.'],['¿Una foto permite confirmar una derivación?','No. Puede aportar contexto si se toma desde un lugar seguro, pero no sustituye las mediciones ni la revisión presencial.']],sources:['insulation','safety'],related:['diferencial-que-no-sube','averias-intermitentes','revision-instalacion-electrica']},
  {slug:'reparacion-cuadros-electricos',name:'Reparación de cuadros',tag:'CUADRO ELÉCTRICO',icon:'panel',photo:'cuadro',
   title:'Reparación y revisión de cuadros eléctricos domésticos',
   intro:'Protecciones que actúan, circuitos sin identificar o señales de deterioro. La revisión del cuadro empieza por el síntoma y continúa con las comprobaciones de la instalación.',
   short:'Comprobación de diferenciales, magnetotérmicos y conexiones del cuadro.',
   sections:[
    ['Cada protección tiene una función','El diferencial y el magnetotérmico no son intercambiables. También puede haber protección frente a sobretensiones. Identificar qué dispositivo actúa ayuda a distinguir el tipo de incidencia.'],
    ['No se trata de poner un automático más grande','Aumentar una protección sin comprobar la sección de los conductores, las cargas y el circuito puede dejar una instalación incorrectamente protegida. La solución debe ser compatible con el conjunto.'],
    ['Reparar o renovar según el estado real','La valoración contempla conexiones, envolvente, identificación de circuitos y protecciones. Se propone el alcance del trabajo después de inspeccionar, sin dar por necesaria una sustitución completa en todos los casos.'],
    ['Olor a quemado, chasquidos o decoloración','No acerques la mano para comprobar la temperatura ni retires la tapa. Mantente alejado del cuadro y solicita ayuda. Si hay humo, fuego o peligro inmediato para las personas, llama al 112.']],
   faq:[['¿Hay que cambiar todo el cuadro?','No siempre. Depende de su estado, de la avería y de las condiciones que debe cumplir la instalación.'],['¿Dais precio antes de empezar?','Consulta las condiciones de desplazamiento y diagnóstico al solicitar el aviso. El alcance de la reparación debe acordarse antes de ejecutarla.']],sources:['rebt','rcd','safety'],related:['diferencial-que-no-sube','sobrecargas-y-cortocircuitos','revision-instalacion-electrica']},
  {slug:'enchufes-e-interruptores',name:'Enchufes e interruptores',tag:'MECANISMOS',icon:'plug',photo:'mecanismos',
   title:'Reparación de enchufes e interruptores averiados',
   intro:'Un enchufe que falla, un mecanismo suelto o una conexión deteriorada necesitan revisión. No basta con cambiar la tapa si el problema está detrás.',
   short:'Mecanismos que no funcionan, conexiones deterioradas y señales de calentamiento.',
   sections:[
    ['Distinguir mecanismo, conexión y circuito','Que un aparato no funcione en una toma no identifica por sí solo la causa. El profesional revisa el mecanismo, su conexión y el circuito que lo alimenta, según el síntoma comunicado.'],
    ['Señales de deterioro que no deben ignorarse','El olor a quemado, el ennegrecimiento o el chisporroteo justifican dejar de utilizar ese punto y pedir ayuda. No toques un mecanismo dañado ni lo abras para comprobar cómo está.'],
    ['Sustitución con revisión de la conexión','La reparación puede afectar al mecanismo y a los materiales deteriorados de su conexión. La revisión no consiste en ocultar marcas de calentamiento con una tapa nueva.'],
    ['Qué información enviar','Indica qué punto falla y desde cuándo. Una imagen exterior solo debe tomarse desde una posición segura, sin desmontar nada ni acercarse a elementos dañados.']],
   faq:[['¿Es normal que un enchufe huela a quemado?','No debe seguir utilizándose. Mantente alejado del punto deteriorado y solicita una revisión.'],['¿Atendéis también interruptores de luz?','Puedes consultar avisos por interruptores, conmutadores y otros mecanismos de la instalación doméstica.']],sources:['safety','rebt'],related:['circuitos-enchufes-alumbrado','sobrecargas-y-cortocircuitos','revision-instalacion-electrica']},
  {slug:'sobrecargas-y-cortocircuitos',name:'Sobrecargas y cortocircuitos',tag:'AUTOMÁTICOS',icon:'bolt',photo:'sobrecarga',
   title:'Automáticos que saltan: sobrecargas y cortocircuitos',
   intro:'Que se corte la luz al conectar un aparato no siempre significa lo mismo. Hay que identificar qué protección actúa y qué parte de la instalación queda afectada.',
   short:'Localización de la causa cuando salta una protección al utilizar la instalación.',
   sections:[
    ['Sobrecarga, cortocircuito o potencia contratada','Son situaciones diferentes. Un circuito puede estar sobrecargado, puede existir un defecto eléctrico o puede actuar el control de potencia. No conviene atribuir cualquier corte a falta de potencia contratada.'],
    ['La pista de los aparatos que estaban funcionando','Explica qué equipos se utilizaban y si el corte fue inmediato o apareció después de un tiempo. No reproduzcas deliberadamente el fallo para grabarlo ni fuerces la reconexión.'],
    ['La protección no debe anularse','El profesional comprueba el circuito y sus receptores antes de proponer cambios. Puentear una protección o aumentar su calibre sin revisar la instalación no es una reparación.'],
    ['Instalación o electrodoméstico','La revisión puede encontrar un defecto en la instalación o señalar un equipo como origen del problema. La reparación interna de ese aparato debe confirmarse con el servicio técnico correspondiente.']],
   faq:[['¿Subir la potencia contratada evita todos los cortes?','No. No corrige un cortocircuito, una derivación ni una conexión deteriorada.'],['¿Podéis decir la causa solo con el nombre del aparato?','No. Se necesita revisar qué protección actúa y comprobar la instalación y el equipo implicado.']],sources:['rebt','supply'],related:['sin-luz-en-casa','diferencial-que-no-sube','reparacion-cuadros-electricos']},
  {slug:'averias-intermitentes',name:'Averías intermitentes',tag:'DIAGNÓSTICO',icon:'meter',photo:'intermitente',
   title:'Averías eléctricas intermitentes: cortes que aparecen y desaparecen',
   intro:'La electricidad vuelve y parece que todo funciona, pero el problema se repite. Anotar cuándo ocurre ayuda a orientar una revisión que puede requerir más de una comprobación.',
   short:'Investigación de fallos que no aparecen de forma constante.',
   sections:[
    ['Anotar el patrón sin provocar el fallo','Registra la hora aproximada, qué zonas se quedaron sin luz y qué equipos estaban en uso. Añade si coincidió con lluvia o una modificación reciente. No hagas pruebas manipulando la instalación.'],
    ['No prometer una causa antes de medir','Las averías intermitentes pueden tener distintos orígenes. No sería riguroso asegurar que basta con cambiar el diferencial o un aparato sin comprobar qué sucede.'],
    ['Acordar el alcance del diagnóstico','Algunas incidencias exigen observar la instalación en distintas condiciones o una revisión adicional. Consulta cómo se plantea ese trabajo y sus condiciones antes de aceptarlo.'],
    ['Cuando hay señales de riesgo','Un fallo intermitente con olor a quemado, chispas o descargas no debe seguir observándose mientras se utiliza la instalación afectada. Mantente alejado y pide ayuda.']],
   faq:[['¿Podéis garantizar resolverlo en una sola visita?','No se puede garantizar antes de conocer el origen y las condiciones de la avería.'],['¿Sirve apuntar cuándo se corta?','Sí. La información sobre el momento y los equipos utilizados ayuda a preparar la revisión.']],sources:['rcd','safety'],related:['humedad-y-derivaciones','diferencial-que-no-sube','circuitos-enchufes-alumbrado']},
  {slug:'circuitos-enchufes-alumbrado',name:'Circuitos y alumbrado',tag:'REPARACIÓN PARCIAL',icon:'bulb',photo:'circuitos',
   title:'Reparación de circuitos de enchufes y alumbrado',
   intro:'Puede fallar una habitación, un grupo de enchufes o una línea de iluminación sin que toda la vivienda se quede sin electricidad.',
   short:'Revisión de zonas de la casa que se quedan sin enchufes o iluminación.',
   sections:[
    ['Delimitar la parte que ha dejado de funcionar','Describe qué estancias o puntos están afectados y cuáles siguen funcionando. No desmontes mecanismos ni cajas para buscar la avería.'],
    ['El fallo puede estar antes del último punto','Una conexión o un circuito puede afectar a varios puntos de uso. La revisión busca el origen, en lugar de cambiar cada enchufe que ha dejado de funcionar.'],
    ['Mecanismos, cableado y receptores','El alcance dependerá de lo que se detecte en la línea de enchufes o alumbrado. La reparación de una luminaria y la sustitución de su electrónica se valoran según el equipo.'],
    ['Planificar el trabajo sin dejar protecciones anuladas','Al solicitar el aviso, indica si necesitas acceso a un falso techo, una zona común o un cuarto de instalaciones. No se propone recuperar el servicio puenteando elementos de seguridad.']],
   faq:[['¿Puede haber una avería si el resto de la casa tiene luz?','Sí. Que otros circuitos funcionen no descarta un fallo en la zona afectada.'],['¿También revisáis luces que fallan?','Puedes consultar la revisión de líneas de alumbrado y sus mecanismos, indicando cuántos puntos están afectados.']],sources:['rebt','safety'],related:['enchufes-e-interruptores','sin-luz-en-casa','averias-intermitentes']},
  {slug:'revision-instalacion-electrica',name:'Revisión de la instalación',tag:'SEGURIDAD',icon:'shield',photo:'revision',
   title:'Revisión de la instalación eléctrica de la vivienda',
   intro:'Una revisión puede valorar el estado del cuadro, los circuitos y las medidas de protección, especialmente cuando hay fallos repetidos o elementos deteriorados.',
   short:'Valoración del estado de protecciones, conexiones y circuitos domésticos.',
   sections:[
    ['La edad no es un diagnóstico','No toda instalación antigua presenta el mismo estado, ni una reforma reciente garantiza que no haya defectos. Conviene explicar qué síntomas existen y qué cambios se han realizado.'],
    ['Definir qué se va a comprobar','Consulta el alcance de la revisión, las comprobaciones previstas y cómo se comunicarán los resultados. La instalación debe valorarse como conjunto, no solo por el aspecto exterior del cuadro.'],
    ['Puesta a tierra y medidas de protección','Las comprobaciones sobre estas medidas corresponden al profesional. No deben improvisarse conexiones de tierra ni anularse protecciones para eliminar una molestia.'],
    ['Revisión no significa certificado automático','Un diagnóstico de averías no equivale por sí mismo a un boletín ni a una inspección reglamentaria. No se anuncian certificados sin confirmar el servicio y la habilitación necesarios.']],
   faq:[['¿Incluye un boletín eléctrico?','No se ofrece como incluido. Hay que confirmar por separado el tipo de documento y quién puede emitirlo.'],['¿Podéis revisar una vivienda antes de una reforma?','Consulta el alcance de la revisión indicando el estado de la vivienda y el trabajo que se plantea.']],sources:['rebt','safety'],related:['reparacion-cuadros-electricos','enchufes-e-interruptores','humedad-y-derivaciones']},
  {slug:'urgencias-electricas',name:'Urgencias eléctricas',tag:'SOLICITAR ASISTENCIA',icon:'phone',photo:'urgencia',
   title:'Electricista 24 horas para urgencias y averías en viviendas',
   intro:'Urgencias eléctricas 24 horas. Describe la avería, indica el municipio y consulta la atención y el desplazamiento. El desplazamiento y las condiciones se confirman antes de organizar la intervención.',
   short:'Consulta de asistencia para apagones particulares y averías domésticas.',
   sections:[
    ['Un aviso claro ayuda a organizar la atención','Indica la localidad, si se ha perdido toda la luz o solo una parte, y si observas alguna señal de riesgo. No hace falta abrir el cuadro para solicitar asistencia.'],
    ['Disponibilidad y coste antes del desplazamiento','Pregunta por la disponibilidad real, las condiciones de desplazamiento, el diagnóstico y cualquier suplemento aplicable. No se publican plazos de llegada ni tarifas que no estén confirmados.'],
    ['Emergencia personal o incendio','Si hay humo, fuego, una descarga con una persona afectada o peligro inmediato, aléjate y llama al 112. Un WhatsApp comercial no sustituye a los servicios de emergencia.'],
    ['No somos la distribuidora eléctrica','Los apagones generales y las incidencias en la red deben notificarse a la distribuidora. El servicio de esta web se centra en consultas de averías de la instalación particular.']],
   faq:[['¿Es un servicio 24 horas?','Sí, se ofrece atención de urgencias eléctricas 24 horas. El desplazamiento concreto debe confirmarse al contactar. No se anuncia una disponibilidad permanente que no esté verificada.'],['¿El mensaje de WhatsApp reserva una visita?','No. Es una solicitud de información; la visita debe ser confirmada.']],sources:['supply','safety'],related:['sin-luz-en-casa','diferencial-que-no-sube','humedad-y-derivaciones']},
];
export const generalFaq = [
 ['¿Qué averías puedo consultar?','Cortes de luz particulares, diferenciales que saltan, fallos del cuadro, enchufes, alumbrado y posibles derivaciones. Describe el problema para confirmar el alcance de la atención.'],
 ['¿Cómo sé si podéis ir a mi pueblo?','Busca tu municipio o consulta directamente por teléfono. La presencia en el directorio permite preparar el aviso; la cobertura y el desplazamiento se confirman antes de concertar la visita.'],
 ['¿Cuánto cuesta una reparación eléctrica?','Depende del desplazamiento, el diagnóstico, la mano de obra y los materiales. Pide las condiciones de atención y acuerda el alcance de la reparación antes de empezar.'],
 ['¿Es necesario mandar una foto del cuadro?','No es obligatorio. Solo envía una imagen exterior si puedes tomarla desde un lugar seguro, sin abrir tapas ni acercarte a elementos mojados o dañados.'],
];
