import fs from 'node:fs/promises';
import path from 'node:path';
import {site,provinces,services,photos} from '../content/site.mjs';
const out=path.resolve('dist');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=p=>`https://images.pexels.com/photos/${p.id}/pexels-photo-${p.id}.jpeg?auto=compress&cs=tinysrgb&w=1400`;
const css=`*{box-sizing:border-box}body{margin:0;font:16px/1.6 system-ui;color:#172b3d}a{color:inherit;text-decoration:none}header{position:sticky;top:0;background:#fff;border-bottom:1px solid #dce4ea;z-index:4}.top{background:#102438;color:#dbe5ed;text-align:center;padding:7px;font-size:12px}nav,.wrap{max-width:1180px;margin:auto;padding-left:24px;padding-right:24px}nav{height:76px;display:flex;align-items:center;justify-content:space-between}.brand{font-size:20px;font-weight:850}.brand b{background:#ffd04a;padding:10px;border-radius:10px;margin-right:8px}.call,.btn{display:inline-block;padding:13px 18px;border-radius:10px;font-weight:800}.call{background:#102438;color:#fff}.hero{background:#f5f8fa}.hero .wrap{padding-top:65px;padding-bottom:65px;display:grid;grid-template-columns:1.05fr .95fr;gap:50px;align-items:center}h1,h2,h3{line-height:1.12;letter-spacing:-.035em}h1{font-size:clamp(42px,5vw,68px);margin:12px 0}h2{font-size:clamp(30px,3vw,44px)}p{color:#526576}.lead{font-size:18px}.hero img,.service img{width:100%;height:460px;object-fit:cover;border-radius:20px}.eyebrow{font-size:12px;letter-spacing:.13em;font-weight:850;color:#607284}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:25px}.yellow{background:#ffd04a}.wa{background:#087a48;color:#fff}.section{padding-top:75px;padding-bottom:75px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:30px}.card{border:1px solid #dce4ea;border-radius:16px;padding:24px;background:#fff}.card h3{font-size:21px}.more{font-weight:800}.notice{background:#fff5d8;border-left:4px solid #d79b00;padding:17px;border-radius:8px;margin:25px 0}.service{display:grid;grid-template-columns:1fr 1fr;gap:35px;align-items:start}.faq details{padding:16px 0;border-bottom:1px solid #dce4ea}.faq summary{font-weight:800}.provinces{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.province{padding:16px;border:1px solid #dce4ea;border-radius:12px;font-weight:750}footer{background:#0b1b2a;color:#dce5ed;padding:40px max(24px,calc((100% - 1132px)/2))}footer p{color:#aab9c5}@media(max-width:760px){nav{height:68px}.hero .wrap,.service{grid-template-columns:1fr}.hero img,.service img{height:320px}.grid,.provinces{grid-template-columns:1fr}.section{padding-top:50px;padding-bottom:50px}.hero .wrap{padding-top:45px;padding-bottom:45px}h1{font-size:42px}.call{font-size:0}.call:after{content:'☎ Llamar';font-size:14px}}`;
const header=()=>`<header><div class="top">Reparaciones eléctricas domésticas · Consulta disponibilidad</div><nav><a class="brand" href="/"><b>⚡</b>Electricista Rápido</a><a class="call" href="tel:${site.tel}">☎ ${site.phone}</a></nav></header>`;
const footer=()=>`<footer><strong>Electricista Rápido</strong><p>Diagnóstico y reparación de averías eléctricas domésticas. Ante incendio o peligro inmediato, llama al 112.</p></footer>`;
const page=(title,desc,body)=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="noindex,follow"><style>${css}</style></head><body>${header()}${body}${footer()}</body></html>`;
const write=async(url,html)=>{const file=path.join(out,url.endsWith('/')?url+'index.html':url);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,html)};
await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});
const cards=services.map(s=>`<article class="card"><small>${esc(s.tag)}</small><h3>${esc(s.name)}</h3><p>${esc(s.short)}</p><a class="more" href="/servicios/${s.slug}/">Ver avería →</a></article>`).join('');
await write('/',page('Electricista Rápido | Averías y reparaciones eléctricas','Electricista para averías domésticas, diferenciales, cuadros, cortocircuitos y problemas por humedad.',`<main><section class="hero"><div class="wrap"><div><div class="eyebrow">AVERÍAS ELÉCTRICAS EN VIVIENDAS</div><h1>¿Sin luz? Buscamos dónde está el problema</h1><p class="lead">Revisión de <strong>diferenciales que saltan, cuadros eléctricos, cortocircuitos, humedad, enchufes y circuitos averiados</strong>.</p><div class="actions"><a class="btn yellow" href="tel:${site.tel}">☎ ${site.phone}</a><a class="btn wa" href="https://wa.me/${site.whatsapp}">WhatsApp</a></div><div class="notice">No fuerces protecciones ni abras el cuadro. Si hay humo, chispas, olor a quemado o agua junto a elementos eléctricos, mantente alejado.</div></div><img src="${img(photos.hero)}" alt="${esc(photos.hero.alt)}"></div></section><section class="wrap section"><div class="eyebrow">¿QUÉ TE OCURRE?</div><h2>Averías explicadas por el síntoma</h2><p class="lead">El objetivo es localizar la causa antes de cambiar piezas.</p><div class="grid">${cards}</div></section><section class="wrap section"><div class="eyebrow">ZONAS</div><h2>Electricista por provincias y pueblos</h2><p>Estamos preparando el directorio municipal completo. La presencia de un municipio no sustituirá la confirmación de cobertura y desplazamiento.</p><div class="provinces">${provinces.map(p=>`<div class="province">Electricista en ${esc(p.name)}</div>`).join('')}</div></section></main>`));
for(const s of services){const p=photos[s.photo]||photos.hero;const blocks=s.sections.map(([h,b])=>`<article class="card"><h3>${esc(h)}</h3><p>${esc(b)}</p></article>`).join('');const faq=s.faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('');await write(`/servicios/${s.slug}/`,page(`${s.name} | Electricista Rápido`,s.intro,`<main class="wrap section"><a href="/">← Inicio</a><section class="service"><div><div class="eyebrow">${esc(s.tag)}</div><h1>${esc(s.title)}</h1><p class="lead">${esc(s.intro)}</p><div class="actions"><a class="btn yellow" href="tel:${site.tel}">☎ Consultar</a><a class="btn wa" href="https://wa.me/${site.whatsapp}">WhatsApp</a></div></div><img src="${img(p)}" alt="${esc(p.alt)}"></section><section class="grid">${blocks}</section><section class="faq section"><h2>Preguntas frecuentes</h2>${faq}</section></main>`))}
await fs.writeFile(path.join(out,'robots.txt'),'User-agent: *\nDisallow: /\n');
await fs.writeFile(path.join(out,'_headers'),'/*\n  X-Robots-Tag: noindex, nofollow\n  X-Content-Type-Options: nosniff\n');
console.log(`BUILD OK: ${services.length+1} páginas. Vista de revisión noindex.`);
